### PR TITLE
Button enhancement

### LINKED ISSUE #45: move the "choose affiliated courses" button
Some feedback suggested to move the choose affiliated courses button, because teachers could think that they should use the buttons in the order they are displayed in.

### PR DESCRIPTION
**Pull request by rtschu**
closes #45 #46

### CODE REVIEW

**Comment by Dagefoerde** [comment]
Seeing that the course mapping button does not submit a form, and is rather a link, it could look a bit more lightweight. Have a look at the screenshot below for an example (blue links in the top right corner):

new_ess

Here's similar code for reference: https://github.com/unirz-tu-ilmenau/moodle-block_opencast/pull/95/files#diff-ecf144e33d13e81a79f4124b4526e3e3R29

**Comment by tobiasreischmann** [comment]
> Seeing that the course mapping button does not submit a form, and is rather a link, it could look a bit more lightweight...

However, we are not in a page context here. We only have the space of a block. Would you suggest to place this blue lightweight link in the right top corner of the block? (I would vote against that)
Or do you want to simply replace the button by this link at the same position?

**Comment by tobiasreischmann** [comment]
@rtschu If you make layout changes, it would be very nice to have a previous/after through screenshots. This way, the peer reviewer do not have to setup a working installation with dummy data, but can solely look at the code and the visual result.
In general the PRs can have more descriptions. Links to related issues are helpful. But you should also add a description what has changed to the PR itself. Looking through the linked issues is tedious.

**Comment by Dagefoerde** [comment]
> > Seeing that the course mapping button does not submit a form, and is rather a link, it could look a bit more lightweight...
> 
> However, we are not in a page context here. We only have the space of a block. Would you suggest to place this blue lightweight link in the right top corner of the block? (I would vote against that)
> Or do you want to simply replace the button by this link at the same position?

The former is exactly what I meant (as this kind of link is in the top right corner of other pages as well). I vote in favor of that because it corresponds to how things are displayed that are part of pages.

**Comment by tobiasreischmann** [comment]
Ok. We dicussed: Can you alter it to be a link as suggested by @Dagefoerde. It should however remain at the same position.

**Comment by Dagefoerde** [comment]
Please see https://github.com/learnweb/moodle-block_evasys_sync/pull/52#pullrequestreview-303256901. Also, is there an update on the placement of the link?
Thanks for making the changes and for all your work!

**Comment by rtschu** [comment]
Did you look for something like this?
Screenshot_2019-10-18 Kurs Test 3

**Comment by Dagefoerde** [comment]
Exactly, but it would be nicer without the underline. You would achieve that by using the CSS classes that were used in the example code that I linked.

**Comment by tobiasreischmann** [comment]
This is the current view:
image

**Comment by Dagefoerde** [comment]
:shipit:

**Pull request merged**
